#@TYPE: Machine
#@NAME: amd-zynqmp
#@DESCRIPTION: Machine configuration for Zynq Ultrascale+ MPSoC

DEFAULTTUNE = "cortexa53"
WRL_ZYNQMP_BOOTBIN_TARGET ??= ""
require ${@bb.utils.contains_any('WRL_ZYNQMP_BOOTBIN_TARGET', 'zcu102', \
		'conf/machine/zcu102-zynqmp.conf', \
		'conf/machine/include/arm/armv8a/tune-cortexa53.inc', d)}

# To eliminate the annoying output by meta-xilinx-standalone/classes/sanity-meta-xilinx-standalone.bbclass
XILINX_WITH_ESW ?= "xsct"

BSP_XILINX_DERIVED:append = " amd-zynqmp"
MACHINE_FEATURES += "ext3 pci usbgadget usbhost vfat keyboard network"
EXTRA_IMAGECMD:jffs2 = "--pad --no-cleanmarkers --eraseblock=128"

KERNEL_IMAGETYPE = "Image"
KERNEL_DEVICETREE:amd-zynqmp = "xilinx/zynqmp-zcu102-rev1.0.dtb"

PREFERRED_PROVIDER_virtual/kernel ??= "linux-yocto"
PREFERRED_VERSION_linux-yocto ?= "6.6%"

MACHINE_EXTRA_RRECOMMENDS = " kernel-modules kernel-devicetree"
IMAGE_FSTYPES += "tar.bz2 wic wic.bmap"

# wic support
WKS_FILE ?= "zynqmp-sdimage.wks"
do_image_wic[depends] += "mtools-native:do_populate_sysroot dosfstools-native:do_populate_sysroot"
IMAGE_BOOT_FILES ?= " Image zynqmp-zcu102-rev1.0.dtb"

# multilib support
MULTILIBS ?= "${@bb.utils.contains_any('MACHINE_FEATURES', 'mali400', '', 'multilib:lib32', d)}"
DEFAULTTUNE:virtclass-multilib-lib32 ?= "armv7athf-neon"
